"""add pdf_path to meal_plans

Revision ID: ae690f835694
Revises: e08d86a915fb
Create Date: 2026-02-03 17:11:40.345492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae690f835694'
down_revision: Union[str, Sequence[str], None] = 'e08d86a915fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_plans', sa.Column('pdf_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meal_plans', 'pdf_path')
    # ### end Alembic commands ###
