"""Add product tables and link ingredients

Revision ID: b39bb66bf7a7
Revises: 9abfaf9be12d
Create Date: 2026-02-14 10:45:00.196267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b39bb66bf7a7'
down_revision: Union[str, Sequence[str], None] = '9abfaf9be12d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('ean', sa.String(length=13), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('package_size', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('calories_per_100g', sa.Float(), nullable=True),
    sa.Column('protein_per_100g', sa.Float(), nullable=True),
    sa.Column('carbs_per_100g', sa.Float(), nullable=True),
    sa.Column('fat_per_100g', sa.Float(), nullable=True),
    sa.Column('fiber_per_100g', sa.Float(), nullable=True),
    sa.Column('sugar_per_100g', sa.Float(), nullable=True),
    sa.Column('salt_per_100g', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_alternatives',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('original_product_id', sa.String(length=36), nullable=False),
    sa.Column('alternative_product_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('original_product_id != alternative_product_id', name='ck_different_products'),
    sa.ForeignKeyConstraint(['alternative_product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['original_product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_availability',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('store_chain', sa.String(length=100), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('last_verified', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'store_chain', name='uq_product_store')
    )
    op.add_column('ingredients', sa.Column('product_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'ingredients', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ingredients', type_='foreignkey')
    op.drop_column('ingredients', 'product_id')
    op.drop_table('product_availability')
    op.drop_table('product_alternatives')
    op.drop_table('products')
    # ### end Alembic commands ###
